### ISSUE TITLE
NativeScript Plugin

### ISSUE THREAD

**Issue by omurtsckr** [FelOrtiz/SunmiV2-Android-Library#1]
Hi.
I couldnt import and work nativescript project. Im getting this error;
"Cannot read property 'sunmiv2' of undefined".
Do you have nativescript plugin for this library?

**Comment by FelOrtiz** [comment]
[nativescript-sunmi-1.0.0.tgz.zip](https://github.com/FelOrtiz/SunmiV2-Android-Library/files/6175933/nativescript-sunmi-1.0.0.tgz.zip)

Unzip it before using
